name: wrfh_gis
channels:
- conda-forge
- nodefaults
dependencies:
- gdal=3.0.4
- hdf5=1.10.5
- icu=64.2
- libgdal=3.0.4
- libnetcdf=4.7.3
- netcdf4=1.5.3
- numpy=1.18.1
- proj=6.3.1
- pyproj=2.6.0
- python=3.6.10
- whitebox=1.2.0